"""HTTP API over the Labour Code retrieval system.

    GET  /health  -- liveness plus what corpus is actually loaded
    POST /chat    -- {"question": "..."} -> {answer, sources, confidence}

The answer is generated by Claude from retrieved article text. The citations
are NOT generated -- they are the article IDs the retriever returned, attached
to the response independently of anything the model writes.
"""

import logging

from pathlib import Path

import anthropic

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse, JSONResponse
from typing import Literal

from pydantic import BaseModel, Field

import config
import gate
import ratelimit
import retrieval

# Populate os.environ from .env at startup so anything reading environment
# variables directly still works locally.
config.load_env_file()

ANSWER_MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 900
TOP_K = 3

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
)
log = logging.getLogger("legal-rag")

app = FastAPI(
    title="legal-rag",
    description="Question answering over the Lithuanian Labour Code",
)

# /chat spends three paid API calls per request (embed, rerank, generate), and
# the URL is public. /health is deliberately not limited so uptime monitoring
# stays free and always available.
limiter = ratelimit.RateLimiter()

INDEX = Path(__file__).parent / "static" / "index.html"


@app.get("/", include_in_schema=False)
def index():
    """The demo UI. One self-contained file -- no build step, no bundler, and
    nothing to serve it but this route."""
    return FileResponse(INDEX, media_type="text/html")


class ChatRequest(BaseModel):
    question: str = Field(min_length=3, max_length=1000)
    # Presentation only. The corpus, the retrieval and the whole benchmark are
    # Lithuanian; "en" asks the model to write its answer in English FROM the
    # same Lithuanian articles. It does not switch to an English source of law.
    lang: Literal["lt", "en"] = "lt"


# Written in the target language on purpose -- instructions in the output
# language control the output more reliably than instructions about it.
#
# The Lithuanian rules are not generic "write well" advice. Each one names a
# real failure observed in production, with the wrong form beside the right
# one, because Lithuanian punishes clipped phrasing far harder than English
# does: an English bullet can stop at a noun, a Lithuanian one that opens in
# the dative has to reach its verb or it is simply ungrammatical.
ANSWER_LANGUAGE = {
    "lt": (
        "Atsakyk lietuviškai, aiškiai ir taisyklinga kalba.\n"
        "Kalbos reikalavimai:\n"
        "- Rašyk pilnais sakiniais. Kiekvienas punktas turi būti baigtas "
        "teiginys su veiksmažodžiu. Rašyk „Darbuotojui priklauso 30 darbo "
        "dienų“, o ne „Aukščiau nurodytoms kategorijoms: 30 darbo dienų“.\n"
        "- Nepalik nebaigtų žodžių junginių — visada nurodyk daiktavardį. "
        "Rašyk „pagimdžius du ar daugiau vaikų“, o ne „pagimdžius du ar "
        "daugiau“.\n"
        "- Apibūdindamas asmenis vartok būdvardžius, o ne prieveiksmius. "
        "Rašyk „jaunesni nei 18 metų“, o ne „jauniau nei 18 metų“.\n"
        "- Derink linksnius, giminę ir skaičių visame sakinyje.\n"
        "- Skaičius rašyk skaitmenimis, ne žodžiais: „20 darbo dienų“, "
        "o ne „dvidešimt darbo dienų“.\n"
        "- Nevartok angliškų žodžių ir nepalik jokio teksto anglų kalba.\n"
        "- Nerašyk antraščių su # ženklu."
    ),
    "en": (
        "Answer in English, clearly and in complete sentences. The articles "
        "are in Lithuanian; translate what they say faithfully and do not add "
        "anything they do not contain. Keep Lithuanian legal terms in brackets "
        "where a precise English equivalent does not exist. Write numbers as "
        "digits, not words. Do not use markdown headings such as # or ##."
    ),
}

REFUSAL = {
    "lt": ("Neturiu pakankamai patikimo pagrindo atsakyti į šį klausimą pagal "
           "Darbo kodeksą. Pasitikslinkite su teisininku ar personalo skyriumi."),
    "en": ("I don't have a confident enough basis in the Labour Code to answer "
           "this. Check with a lawyer or your HR department."),
}


def build_prompt(question, results, lang="lt"):
    """Give the model only the retrieved articles, and require a citation.

    The citation format stays "[X straipsnis]" in both languages, because the
    UI parses it back into a link to the source card -- and because the article
    is a Lithuanian one whichever language the prose is in.
    """
    articles = "\n\n".join(
        f"[{r['citation']} straipsnis] {r['title']}\n{r['text']}" for r in results
    )
    return (
        "Tu esi Lietuvos darbo teisės asistentas. Atsakyk į klausimą remdamasis "
        "TIK žemiau pateiktais Darbo kodekso straipsniais. Jei straipsniuose "
        "atsakymo nėra, pasakyk, kad nežinai.\n\n"
        f"Straipsniai:\n{articles}\n\n"
        f"Klausimas: {question}\n\n"
        f"{ANSWER_LANGUAGE[lang]} Pabaigoje nurodyk straipsnį formatu "
        "[X straipsnis]."
    )


def generate_answer(question, results, lang="lt"):
    client = anthropic.Anthropic(api_key=config.require("ANTHROPIC_API_KEY"))
    response = client.messages.create(
        model=ANSWER_MODEL,
        max_tokens=MAX_TOKENS,
        messages=[
            {"role": "user", "content": build_prompt(question, results, lang)}
        ],
    )
    # Join every text block. content[0] is not always the answer -- a model
    # with extended thinking enabled returns a thinking block first, and
    # indexing blindly would crash on it.
    return "".join(
        block.text for block in response.content
        if getattr(block, "type", None) == "text"
    )


@app.get("/health")
def health():
    """Reports what is actually loaded, not just that the process is alive.

    A health check that only returns {"ok": true} cannot distinguish a working
    service from one serving an empty or mismatched corpus.
    """
    return {
        "status": "ok",
        "articles": len(retrieval.ARTICLES),
        "vectors": list(retrieval.VECTORS.shape),
        "embedding_model": retrieval.SIDECAR["model"],
        "answer_model": ANSWER_MODEL,
        "edition_from": retrieval.SIDECAR["edition_from"],
        "edition_to": retrieval.SIDECAR["edition_to"],
        "threshold": gate.THRESHOLD,
        "rerank_model": retrieval.RERANK_MODEL,
        "languages": ["lt", "en"],
        "usage": limiter.stats(),
    }


@app.post("/chat")
def chat(request: ChatRequest, http: Request):
    denied = limiter.check(ratelimit.client_ip(http))
    if denied:
        status, reason, retry_after = denied
        log.warning("blocked ip=%s reason=%s", ratelimit.client_ip(http), reason)
        return JSONResponse(
            status_code=status,
            headers={"Retry-After": str(retry_after)},
            content={
                "answer": None,
                "error": reason,
                "detail": (
                    "This is a public demo with a spending cap. "
                    "Try again later, or run it yourself: "
                    "https://github.com/dziugasmarcenas-ui/legal-rag"
                ),
                "retry_after_seconds": retry_after,
            },
        )

    results = retrieval.retrieve(request.question, k=TOP_K)
    # report the same quantity the gate decides on, never a different one
    confidence = max((r[gate.SIGNAL] for r in results), default=0.0)

    # Sources are attached whether or not we answer, so a refusal still shows
    # what was considered and at what score. Refusing invisibly is not honest.
    sources = [
        {
            "article": r["article"],
            "citation": r["citation"],
            "title": r["title"],
            "cosine_score": round(r["cosine_score"], 4),
            "rerank_score": round(r["rerank_score"], 4) if r["rerank_score"] is not None else None,
        }
        for r in results
    ]

    if not gate.should_answer(results):
        log.info("refused q=%r confidence=%.4f", request.question, confidence)
        return {
            "answer": REFUSAL[request.lang],
            "sources": sources,
            "confidence": round(confidence, 4),
            "confidence_signal": "max_" + gate.SIGNAL,
            "refused": True,
        }

    try:
        answer = generate_answer(request.question, results, request.lang)
    except anthropic.APIStatusError as error:
        # The model API failing is not the same as having no answer. Say so,
        # and still return the retrieved sources -- they were computed locally
        # and are useful on their own.
        log.error("anthropic %s: %s", error.status_code, error)
        return {
            "answer": None,
            "error": "answer_generation_unavailable",
            "sources": sources,
            "confidence": round(confidence, 4),
            "confidence_signal": "max_" + gate.SIGNAL,
            "refused": False,
        }

    log.info("answered q=%r confidence=%.4f", request.question, confidence)
    return {
        "answer": answer,
        "sources": sources,
        "confidence": round(confidence, 4),
        "confidence_signal": "max_" + gate.SIGNAL,
        "refused": False,
    }
